version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
        
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data

    ports:
      - "9200:9200"
    networks:
      - observability

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOST: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    networks:
      - observability
    depends_on:
      - elasticsearch
networks:
  observability:
    driver: bridge